[[main]]
  name = "Blog Posts"
  pageRef = "blog"
  weight = 10

[[main]]
  name = "Data Science"
  pageRef = "tags/data-science"
  weight = 15

[[main]]
  name = "Web Dev"
  pageRef = "tags/web-development"
  weight = 16

[[main]]
  name = "Topics"
  pageRef = "tags"
  weight = 20

[[main]]
  pre = "github"
  name = "GitHub"
  url = "https://github.com/joush007"
  weight = 30

[[footer]]
  name = "About"
  url = "/about"
  weight = 10

[[footer]]
  name = "GitHub Repo"
  url = "https://github.com/joush007/joush007.github.io"