colorScheme = "blowfish"
defaultAppearance = "dark"
enableSearch = true
enableCodeCopy = true
defaultBackgroundImage = "img/small_walrus_portal.jpg"

[homepage]
layout = "background"
showRecent = true
showRecentItems = 4
homepageImage = "img/portal_to_walrus_big_walrus.jpg"
layoutBackgroundBlur = true
cardViewScreenWidth = true

[article]
showDate = true
showTaxonomies = true
showAuthorsBadge = true
showHero = true
heroStyle = "thumbAndBackground"

[list]
cardView = true
showCards = true
layoutBackgroundHeaderSpace = true
showHero = true
heroStyle = "basic"

[verification]
google = "Tpd548gKcH4khlvrwUJiDWt6JFmIXwdw0PvQufl5oEk"